blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'
# blog/
urlpatterns = [
    path('', views.blog, name='home'),
    path('<int:post_id>/', views.post, name='post'),
    path('example/', views.example, name='example'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

# HTTP Request < > HTTP Response
# MVT - Model View Template
# MVC - Model View Controller




urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),

]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from typing import Any

from blog.data import posts
from django.http import HttpRequest, Http404
from django.shortcuts import render
# Create your views here.


def blog(request):
    context = {
        # 'text': 'Blog Page',
        'posts': posts,
    }

    return render(
        request,
        'blog/index.html',
        context
    )

def post(request: HttpRequest, post_id:int):
    found_post: dict[str, Any] | None = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
    if found_post is None:
        raise Http404('Post não existe.')

        
    context= {
        # 'text': 'Blog Page',
        'post': found_post,
        'title': found_post['title'] + ' - ',
    }
    
    return render(
        request,
        'blog/post.html',
        context,
)


def example(request):
    context = {
        'text': 'Example Blog Page',
        'title': 'Site do Ailton',
    }
 
    return render(
        request,
        'blog/example.html',
        context,
)

home/views.py
from django.shortcuts import render


def home(request):
    return render(
        request,
        'home/index.html',
        {
            'text': 'Home Page',
            'year': 2025,
        },
                  

)

blog/templates/blog/example.html
{% extends "global\base.html" %}
{% block texto %}
    {{ text }} - Welcome to the Example Page! The year is {{ year }}.
{% endblock texto %}

blog/templates/blog/index.html
{% extends 'global/base.html' %}
{% block texto %} {{ text }} {% endblock texto %}

{%block posts %}
    {% for post in posts %}
        {% include 'global/partials/postblock.html' %}
    {% endfor %}
{%endblock posts %}

blog/templates/blog/post.html
{% extends 'global/base.html' %}
{% block texto %} {{ text }} {% endblock texto %}

{%block posts %}
    <article class="post single-post">
        <header>
            <h1 class="post__title">
                <a href="{% url 'blog:post' post.id %}">
                {{ post.title }}
            </a>
        </h1>
        </header>
        <div class="post__body"> {{ post.title }} </div>        
    </article>

{%endblock posts %}

home/templates/home/index.html
{% extends "global/base.html" %}
{% block texto %}
    {{ text }} - Welcome to the Home Page! The year is {{ year }}.
{% endblock texto %}

{%block home %}
    <h1> Welcome to the Home Block of the Blog! </h1>
{%endblock home %}D: